[0m16:56:03.937708 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93dbcba050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93dae7f970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93dae7fb80>]}


============================== 16:56:03.939658 | 8de70fbc-a45a-44c5-97ac-2ca28a3ba8e7 ==============================
[0m16:56:03.939658 [info ] [MainThread]: Running with dbt=1.9.4
[0m16:56:03.939988 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/ajinfrankj/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:56:03.940316 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ajinfrankj/airflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:56:03.940893 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.039452944, "process_in_blocks": "20128", "process_kernel_time": 0.113303, "process_mem_max_rss": "94964", "process_out_blocks": "8", "process_user_time": 0.906424}
[0m16:56:03.941203 [debug] [MainThread]: Command `dbt run` failed at 16:56:03.941125 after 0.04 seconds
[0m16:56:03.941438 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93dbcba050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93db54ec80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f93dae7d060>]}
[0m16:56:03.941682 [debug] [MainThread]: Flushing usage events
[0m16:56:04.044879 [debug] [MainThread]: An error was encountered while trying to flush usage events
